name: pull upstream changes for new untranslated strings (ID)
run-name: pull upstream changes for new untranslated strings (ID)
on: [push]
jobs:
  pull-new-strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git remote add upstream https://github.com/kodebanget/bluesky-social-app.git
      - run: git fetch upstream main
      - run: |
          git checkout main
          FILE_IS_UPDATED=$(git diff --compact-summary main upstream/main | grep 'id/messages.po')
          echo $FILE_IS_UPDATED
          if [ "$FILE_IS_UPDATED" != "" ]; then
            git merge upstream/main
            git push origin main
          fi
